# Generated by Django 2.2 on 2019-05-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('pic_url', models.CharField(blank=True, default='', max_length=200)),
                ('first_login_time', models.DateTimeField(auto_now_add=True, verbose_name='首次登录时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='最近活动时间')),
                ('fb_id', models.CharField(max_length=100, null=True)),
                ('google_id', models.CharField(max_length=100, null=True)),
                ('line_id', models.CharField(max_length=100, null=True)),
                ('bean', models.IntegerField(default=0)),
                ('invite_code', models.CharField(max_length=10)),
                ('login_type', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=200)),
                ('invited', models.CharField(max_length=10, null=True)),
                ('progress', models.IntegerField(default=1, verbose_name='完成邀请任务的进度')),
                ('friends', models.ManyToManyField(to='user.UserInfo')),
            ],
            options={
                'ordering': ('first_login_time',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtain_time', models.DateTimeField(auto_now_add=True, verbose_name='券获得时间')),
                ('effective_time', models.CharField(max_length=20, verbose_name='券有效时间')),
                ('free_ads_day', models.IntegerField(default=1, verbose_name='免广告的天数')),
                ('status', models.BooleanField(default=False, verbose_name='券是否已经使用')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=20)),
                ('task_desc', models.CharField(default='', max_length=100)),
                ('task_time', models.DateField(auto_now_add=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_sign_day', models.IntegerField(default=1)),
                ('pre_sign_day', models.CharField(max_length=30)),
                ('sign_bean', models.IntegerField(default=50)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RechargeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean', models.IntegerField()),
                ('money', models.FloatField(null=True)),
                ('recharge_time', models.DateTimeField(auto_now_add=True)),
                ('recharge_desc', models.CharField(default='', max_length=100)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'ordering': ('recharge_time',),
            },
        ),
        migrations.CreateModel(
            name='ConsumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_time', models.DateTimeField(auto_now_add=True)),
                ('bean', models.IntegerField()),
                ('book_name', models.CharField(max_length=30)),
                ('chapter_name', models.CharField(max_length=30)),
                ('chapter_count', models.IntegerField()),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
